version: '3.2'

services:
  customer-service :
    container_name: customer
    image: java:8
    depends_on:
    - customer-db
    ports:
    - 8080:8080
    volumes:
    - ./target/wit-customer.jar:/usr/share/service/wit-customer.jar
    entrypoint: java -jar /usr/share/service/wit-customer.jar
  customer-db:
    container_name: app-customer-db
    image: postgres:latest
#    volumes:
#    - app-customer-db:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=customer
    - POSTGRES_PASSWORD=customer
    - POSTGRES_DB=customer
    ports:
    - 5432:5432


#volumes:
#  app-customer-db: {}